services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports: [ "8080:8080" ]

  app-aot:
    profiles: [ "aot" ]
    build:
      context: ..
      dockerfile: docker/Dockerfile.aot
    ports: [ "8081:8080" ]

  app-cds:
    profiles: [ "cds" ]
    build:
      context: ..
      dockerfile: docker/Dockerfile.cds
    ports: [ "8082:8080" ]

  app-native:
    profiles: [ "native" ]
    build:
      context: ..
      dockerfile: docker/Dockerfile.native
    ports: [ "8083:8080" ]
